@baseUrl = http://localhost:3000

### Health
GET {{baseUrl}}/health

###

### Apprenants - Liste
GET {{baseUrl}}/api/apprenants

###

### Apprenants - Création
POST {{baseUrl}}/api/apprenants
Content-Type: application/json

{
  "email": "fred.guiot@gmail.com",
  "nom": "guiot",
  "prenom": "fred"
}

###

### Formations - Création
POST {{baseUrl}}/api/formations
Content-Type: application/json

{
  "titre": "Formation Training",
  "prix": 2000
}


###

### Commandes - Création
POST {{baseUrl}}/api/commandes
Content-Type: application/json

{
  "apprenantId": 2,
  "etat": "payé"
}

### Commandes - Ajouter formation
POST {{baseUrl}}/api/commandes/2/lignes
Content-Type: application/json

{
  "formationId": 1,
  "quantite": 1
}

###

### Commandes - Liste
GET {{baseUrl}}/api/commandes


### Commandes - Liste
GET {{baseUrl}}/api/apprenants

### Commandes - Liste
GET {{baseUrl}}/api/formations
